import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "../components/providers/redux-provider";
import { CartInitializer } from "../components/providers/cart-initializer";
import {AuthInitializer} from "../components/providers/auth-initializer";
import { ToastProvider } from "../components/providers/toast-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReduxProvider>
          <AuthInitializer/>
           <CartInitializer />
           {children}
           <ToastProvider />
        </ReduxProvider>
      </body>
    </html>
  );
}
